image: 'maven:3-jdk-11'

stages:
  - test
  - build

services:
  - 'mysql:5.5'
  - 'mongo:3.4-jessie'

variables:
  MYSQL_DATABASE: "Movie_Cruiser"
  MYSQL_URL: "jdbc:mysql://localhost:3306/Movie_Cruiser?useSSL=false&createDatabaseIfNotExist=true"
  MYSQL_USER: "sandeep"
  MYSQL_PASSWORD: "sandeep"
  MYSQL_ROOT_PASSWORD: "very_strong_password"
  MONGO_DATABASENAME: "MovieCruiser"
  MONGO_URL: "mongodb://localhost:27017/MovieCruiser"

cache:
  paths:
    - .m2/repository
    - target

maven-test:
  stage: test
  script: "mvn test"

maven-build:
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - target/*.jar