FROM java:jre-11.0.6_10-alpine
WORKDIR /usr/src
ADD ./target/Netflix-EurekaNamingService-0.0.1-SNAPSHOT.jar Netflix-EurekaNamingService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "Netflix-EurekaNamingService-0.0.1-SNAPSHOT.jar"]